[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "../backend/static"

[serve]
# The address to serve on.
addr = "0.0.0.0"
# The port to serve on.
port = 5000
# Open a browser tab once the initial build is complete.
open = true
# Disable auto-reload of the web app.
no_autoreload = false
