[package]
name = "load_balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.5.4"
actix-files = "0.5"
actix-web = "3"
clap = { version = "3.0.10", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"